import React from 'react'; 

export const grainLabels = {
    "bagel_large": "How many large bagels do you have?", 
    "bagel_mini": "How many mini bagels do you have?", 
    "biscuit_large": "How many large biscuits do you have?", 
    "biscuit_small": "How many small biscuits do you have?", 
    "bread_loaf": "How many loaves of bread (not rye) do you have?", 
    "bread_slice": "How many slice(s) of bread (not rye) do you have? ",
    "rye_loaf": "How many loaves of rye bread do you have? ",
    "rye_slice": "How many slice(s) of rye bread do you have? ",
    "bulgur": "How many cups of bulgur do you have? ", 
    "cornbread_medium": "How many medium slices of cornbread do you have?", 
    "cornbread_small": "How many small slices of cornbread do you have?", 
    "cracker_rs": "What is the number of servings per your package of crackers?", 
    "cracker_wr": "What is the number of servings per your package of crackers?", 
    "english_muffin": "How many english muffins do you have?", 
    "large_muffin": "How many large muffins do you have?", 
    "small_muffin": "How many small muffins do you have?", 
    "oatmeal_cups": "How many cups of oatmeal do you have?", 
    "oatmeal_packet": "How many oatmeal packets do you have?", 
    "pancakes": "How many pancakes do you have?",  
    "popcorn": "How many bags of popcorn do you have?", 
    "ready_breakfast_cereal_cup": "How many cups of breakfast cereal do you have?", 
    "ready_breakfast_cereal_box": "How many boxes of breakfast cereal do you have?",
    "rice": "How many ounces of rice do you have? 1 lb = 16 oz", 
    "pasta": "How many ounces of pasta do you have? 1 lb = 16 oz", 
    "pasta_box": "How many boxes of pasta do you have?", 
    "tortillas_flour_large": "How many large flour tortillas do you have?",
    "tortillas_flour_small": "How many small flour tortillas do you have?",
    "tortillas_flour_corn": "How many corn tortillas do you have?"
}; 
export const vegLabels = {
    "broccoli_oz": "ounces of broccoli", 
    "broccoli_fl": "5 inch, spears of broccoli (3 spears, raw or cooked) ", 
    "greens": "ounces of greens",
    "spinach": "ounces of raw spinach",
    "spinach_cooked": "ounces of cooked spinach",
    "raw_leafy_greens": "ounces of raw, leafy greens (Spinach, romaine, watercress, dark green leafy lettuce, endive, escarole)",
    "carrots": "ounces of carrots",
    "carrot_med": "medium sized carrots", 
    "carrot_mini": "mini sized carrots",  
    "pumpkin": "ounces of pumpkin",
    "red_peppers": "ounces of red or green peppers",
    "pepper_large": "large peppers",
    "pepper_sm": "small peppers",
    "tomato_lg": "large tomatoes (raw)",
    "tomato_oz": "ounces of tomatoes (chopped, sliced, raw, canned or cooked)",
    "tomato_sm": "small tomatoes (raw)",
    "tomato_juice": "ounces of tomatoe juice",
    "sweet_potato_lg": "large, baked sweet potatoes",
    "sweet_potato_sliced": "sliced or mashed, cooked sweet potatoes",
    "winter_squash": "ounces of winter squash (acorn, butternut, hubbard)",
    "acornSquash": "acorn squashes", 
    "dry_beans_n_peas": "dried beans and peas (black, garbanzo, pinto, kidney, soy, etc. ",
    "corn": "ounces of corn (white or yellow)",
    "corn_large": "large ears of corn",
    "corn_small": "small ears of corn",
    "green_peas": "ounces of green peas",
    "white_potatoes": "ounces of white potatoes",
    "bakedoBoiled_potatoe": "medium boiled or baked potatoes", 
    "bean_sprouts": "ounces of bean sprouts",
    "cabbage": "ounces of cabbage",
    "cauliflower": "ounces of cauliflower",
    "celery": "ounces of celery",
    "celery_lg": "large stalks of celery (11-12 inches long)", 
    "cucumbers": "ounces of cucumbers",
    "green_beans": "ounces of green or wax beans",
    "lettuce": "ounces of lettuce (iceberg or head)",
    "mushrooms": "ounces of mushrooms",
    "onions": "ounces of unions",
    "summer_squash_o_zucchini": "ounces of summer squash or zucchini" 
}; 
export const fruitLabels = {
    "apple_small": "How many small apples do you have?",  
    "apple_large": "How many large apples do you have?", 
    "applesauce_1oz": "How many ounces of applesauce do you have?", 
    "applesauce_snackcup": "How many snack cups of applesauce do you have?", 
    "banana_reg": "How many regular bananas do you have?",   
    "banana_small": "How many small bananas do you have?",   
    "cantaloupe": "How many cantalopes do you have?", 
    "grapes": "How many bunches of grapes do you have?", 
    "grapefruit": "How many grapefruits do you have?", 
    "mixed_fruit": "How many snack cups of mixed fruit (fruit cocktail) do you have?", 
    "orange": "How many how many large oranges do you have?",  
    "mandarin_orange": "How many small (mandarin) oranges do you have?", 
    "peach_large": "How many large peaches do you have?",
    "peach_small": "How many small peaches do you have?", 
    "peach_snackcup": "How many peach snack cups do you have?", 
    "pear": "How many pears do you have?", 
    "pear_snackcup": "How many pear snack cups do you have?", 
    "pineapple": "How many pineapples do you have?", 
    "plum_large": "How many large plums do you have?", 
    "plum_small": "How many small plums do you have?", 
    "strawberries": "How many strawberries do you have?", 
    "watermelon": "How many watermellons do you have?"  
}; 
export const dairyLabels = {
    "milk_gallon": "gallons of milk", 
    "milk_half_gallon": "half gallons of milk", 
    "milk": "ounces of milk", 
    "milk_half_pint": "half-pints of milk", 
    "milk_evap_large": "large evaporated milk containers", 
    "milk_evap_small": "small evaporated milk containers", 
    "yogurt": "ounces of yogurt", 
    "yogurt_regularContainer": "regular containers of yogurt (8 oz)", 
    "yogurt_smallContainer": "small containers of yogurt (6 oz)", 
    "yogurt_snackSize": "snack size containers of yogurt(4 oz)", 
    "hard_cheese": "1 and 1/2 ounces of hard cheese", 
    "slice_hard_cheese": "slices of hard cheese",
    "shredded_cheese": "ounces of shredded cheese", 
    "processed_cheese": "ounces of processed cheese (American)",
    "slice_processed": "slices of processed cheese",
    "ricotta": "ounces of ricotta cheese", 
    "cottage_cheese": "cups of collage cheese",   
    "pudding": "ounces of pudding", 
    "froyo_carton": "cartons of frozen yogurt", 
    "froyo": "ounces of frozen yogurt", 
    "icecream_carton": "cartons of ice cream", 
    "icecream": "ounces of ice cream", 
    "icecream_scoop": "scoops of ice cream", 
    "soymilk_calc": "ounces of soymilk", 
    "soymilk_halfpint": "half-pints of soymilk"
}; 
export const proteinLabels = {
    "meat_lean_un": "uncooked Lean Meats (pork, ham, beef, lamb, etc.) in ounces", 
    "meat_lean_cooked": "cooked Lean Meats (pork, ham, beef, lamb, etc.) in ounces", 
    "small_steak": "small steaks (4 oz)", 
    "chicken_turkey_un": "uncooked Chicken or Turkey (without skin) in ounces", 
    "chicken_turkey_cooked": "cooked Chicken or Turkey (without skin) in ounces", 
    "slice_turkey": "sandwich slices of Turkey (1 slice)", 
    "chick_breast": "uncooked Chicken Breasts (4 oz)", 
    "chick_breast_small_cooked": "small cooked Chicken Breasts", 
    "half_cornHen": "1/2 cooked Cornish Game Hens", 
    "whole_cornHen": "whole Cornish Game Hens", 
    "uncooked_fish": "uncooked Fish or Shell Fish (ounces)", 
    "cooked_fish": "cooked Fish or Shell Fish (ounces)", 
    "tuna": "cans of tuna, drained (can)", 
    "salmon_steaks": "Salmon steaks", 
    "small_trout": "small Trout", 
    "eggs": "eggs", 
    "eggWhites": "3 egg whites", 
    "eggYolks": "3 egg yolks", 
    "nuts": "nuts (ounces)", 
    "almonds": "almonds (in portions of 12)", 
    "pistachios": "pistachios (in portions of 24)", 
    "walnut": "walnut halves (in portions of 7)", 
    "seeds": "seeds (ounces)", 
    "tb_peanut": "table spoons/half ounces of Peanut Butter or Almond Butter", 
    "peanut_small": "Peanut Butter (16 oz jar)", 
    "peanut_large": "Peanut Butter (40 oz jar)", 
    "beans_oz": "Beans (black, kidney, pinto, or white beans) in ounces", 
    "cooked_peas": "Cooked Peas (chickpeas, cowpeas, lentils, or split peas) in ounces", 
    "baked_beans": "Baked beans or Refried beans (ounces)", 
    "tofu": "Tofu(s) (ounces)", 
    "tempeh": "Tempeh(s), cooked (ounces)", 
    "soybeans": "roasted soybeans (ounces)", 
    "falafel": "Falafel patties (4 oz)", 
    "hummus_oz": "hummus(es) (ounces)", 
    "hummus_container": "hummus containers (10 oz)", 
    "beans_can": "can of Beans (14 oz)",
            
}; 

/*******************************************************************************
 * Now quantities in oz * 
 ******************************************************************************/

export const grainQuantities = {
    "bagel_large": 4, 
    "bagel_mini": 1, 
    "biscuit_large": 2, 
    "biscuit_small": 1, 
    "bread_loaf":  18,
    "bread_slice": 1,
    "rye_loaf": 4.5,
    "rye_slice": 0.25,
    "bulgur": 2, 
    "cornbread_medium": 2, 
    "cornbread_small":  1, 
    "cracker_rs": 1,  // per serving size of 7 crackers
    "cracker_wr":  1, // per serving size of 5 crackers
    "english_muffin": 2, 
    "large_muffin": 3, 
    "small_muffin": 1, 
    "oatmeal_cups": 1, 
    "oatmeal_packet": 1, 
    "pancakes": 1,  
    "popcorn": 2, 
    "ready_breakfast_cereal_cup": 1, 
    "ready_breakfast_cereal_box": 11,
    "rice": 1, // default value, do actual calculation
    "pasta": 1, // defualt value, do calculation
    "pasta_box": 8, 
    "tortillas_flour_large": 4, 
    "tortillas_flour_small": 1, 
    "tortillas_flour_corn": 1
}; 

export const vegQuantities = {
    "broccoli_oz": 1, 
    "broccoli_fl": 8, 
    "greens": 1,
    "spinach": 0.5,
    "spinach_cooked": 1,
    "raw_leafy_greens": 0.5,
    "carrots": 1,
    "carrot_med": 4, 
    "carrot_mini": 0.67,  
    "pumpkin": 1,
    "red_peppers": 1,
    "pepper_large": 8,
    "pepper_sm": 4,
    "tomato_lg": 8,
    "tomato_oz": 1,
    "tomato_sm": 4,
    "tomato_juice": 1,
    "sweet_potato_lg": 8,
    "sweet_potato_sliced": 1,
    "winter_squash": 1,
    "acornSquash": 12, 
    "dry_beans_n_peas": 1,
    "corn": 1,
    "corn_large": 8,
    "corn_small": 4,
    "green_peas": 1,
    "white_potatoes": 1,
    "bakedoBoiled_potatoe": 8, 
    "bean_sprouts": 1,
    "cabbage": 1,
    "cauliflower": 1,
    "celery": 1,
    "celery_lg": 4,
    "cucumbers": 1,
    "green_beans": 1,
    "lettuce": 0.5,
    "mushrooms": 1,
    "onions": 1,
    "summer_squash_o_zucchini": 1
}

export const fruitQuantities = {
    "apple_small": 4,  
    "apple_large": 8, 
    "applesauce_1oz": 12/31, 
    "applesauce_snackcup": 4, 
    "banana_reg": 8,   
    "banana_small": 4,   
    "cantaloupe": 32, 
    "grapes": 24, 
    "grapefruit": 8, 
    "mixed_fruit": 3, 
    "orange": 8,  
    "mandarin_orange": 4, 
    "peach_large": 8,
    "peach_small": 4, 
    "peach_snackcup": 3, 
    "pear": 8, 
    "pear_snackcup": 3.04, 
    "pineapple": 36, 
    "plum_large": 4, 
    "plum_small": 2.67, 
    "strawberries": 1, 
    "watermelon": 256 
    // "dried_fruit": "", 
    // "fruit_juice": ""  
}; 

export const dairyQuantities = {
    "milk_gallon": 128, 
    "milk_half_gallon": 64, 
    "milk": 1, 
    "milk_half_pint": 8, 
    "milk_evap_large": 24, 
    "milk_evap_small": 10, 
    "yogurt": 1, 
    "yogurt_regularContainer": 8, 
    "yogurt_smallContainer": 6, 
    "yogurt_snackSize": 4, 
    "hard_cheese": 8, 
    "slice_hard_cheese": 4,
    "shredded_cheese": 3, 
    "processed_cheese": 4,
    "slice_processed": 2.67,
    "ricotta": 4, 
    "cottage_cheese": 4,   
    "pudding": 1, 
    "froyo_carton": 48, 
    "froyo": 1, 
    "icecream_carton": 32, 
    "icecream": .67, 
    "icecream_scoop": 2.67, 
    "soymilk_calc": 1, 
    "soymilk_halfpint": 8
}; 
export const proteinQuantities = {
    "meat_lean_un": "uncooked Lean Meats (pork, ham, beef, lamb, etc.) in ounces", 
    "meat_lean_cooked": "cooked Lean Meats (pork, ham, beef, lamb, etc.) in ounces", 
    "small_steak": "small steaks (4 oz)", 
    "chicken_turkey_un": "uncooked Chicken or Turkey (without skin) in ounces", 
    "chicken_turkey_cooked": "cooked Chicken or Turkey (without skin) in ounces", 
    "slice_turkey": "sandwich slices of Turkey (1 slice)", 
    "chick_breast": "uncooked Chicken Breasts (4 oz)", 
    "chick_breast_small_cooked": "small cooked Chicken Breasts", 
    "half_cornHen": "1/2 cooked Cornish Game Hens", 
    "whole_cornHen": "whole Cornish Game Hens", 
    "uncooked_fish": "uncooked Fish or Shell Fish (ounces)", 
    "cooked_fish": "cooked Fish or Shell Fish (ounces)", 
    "tuna": "cans of tuna, drained (can)", 
    "salmon_steaks": "Salmon steaks", 
    "small_trout": "small Trout", 
    "eggs": "eggs", 
    "eggWhites": "3 egg whites", 
    "eggYolks": "3 egg yolks", 
    "nuts": "nuts (ounces)", 
    "almonds": "almonds (in portions of 12)", 
    "pistachios": "pistachios (in portions of 24)", 
    "walnut": "walnut halves (in portions of 7)", 
    "seeds": "seeds (ounces)", 
    "tb_peanut": "table spoons/half ounces of Peanut Butter or Almond Butter", 
    "peanut_small": "Peanut Butter (16 oz jar)", 
    "peanut_large": "Peanut Butter (40 oz jar)", 
    "beans_oz": "Beans (black, kidney, pinto, or white beans) in ounces", 
    "cooked_peas": "Cooked Peas (chickpeas, cowpeas, lentils, or split peas) in ounces", 
    "baked_beans": "Baked beans or Refried beans (ounces)", 
    "tofu": "Tofu(s) (ounces)", 
    "tempeh": "Tempeh(s), cooked (ounces)", 
    "soybeans": "roasted soybeans (ounces)", 
    "falafel": "Falafel patties (4 oz)", 
    "hummus_oz": "hummus(es) (ounces)", 
    "hummus_container": "hummus containers (10 oz)", 
    "beans_can": "can of Beans (14 oz)",        
}; 